Fix the git detection properly

diff --git a/bin/updateShell b/bin/updateShell
--- a/bin/updateShell
+++ b/bin/updateShell
@@ -8,7 +8,7 @@ require_clean_work_tree () {
     # Disallow unstaged changes in the working tree
     if ! git diff-files --quiet --ignore-submodules --
     then
-        echo >&2 "cannot $1: you have unstaged changes."
+        echo -e "\t" >&2 "cannot $1: you have unstaged changes."
         git diff-files --name-status -r --ignore-submodules -- >&2
         err=1
     fi
@@ -16,14 +16,14 @@ require_clean_work_tree () {
     # Disallow uncommitted changes in the index
     if ! git diff-index --cached --quiet HEAD --ignore-submodules --
     then
-        echo >&2 "cannot $1: your index contains uncommitted changes."
+        echo -e "\t" >&2 "cannot $1: your index contains uncommitted changes."
         git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
         err=1
     fi
 
     if [ $err = 1 ]
     then
-        echo >&2 "Please commit or stash them."
+        echo -e "\t" >&2 "Please commit or stash them."
         return 1
     fi
 
@@ -32,14 +32,18 @@ require_clean_work_tree () {
 
 # Update dotfiles
 echo Updating dotfiles:
-pushd $ZSH
-cleanTree=require_clean_work_tree
-if [ $cleanTree == 0 ]; then
+
+pushd $ZSH > /dev/null
+
+require_clean_work_tree "update dotfiles"
+
+if [ $? -eq 0 ]; then
     git pull --prune --rebase
-else
-    echo -e "\t" Commit changes in dotfiles first
 fi
-popd
+
+popd > /dev/null
+
+exit
 
 # Update Vundle
 echo Updating Vundle:
