Change clean working tree detection to actually work

diff --git a/bin/updateShell b/bin/updateShell
--- a/bin/updateShell
+++ b/bin/updateShell
@@ -1,26 +1,41 @@
 #!/bin/bash
 
-function git_dirty {
-    [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && echo "*"
-}
+require_clean_work_tree () {
+    # Update the index
+    git update-index -q --ignore-submodules --refresh
+    err=0
 
-function git_untracked {
-    expr `git status --porcelain 2>/dev/null| grep "^??" | wc -l`
-}
-
-function git_clean {
-    if [ git_dirty != * && git_untracked == 0 ]; then
-        echo true
-    else
-        echo false
+    # Disallow unstaged changes in the working tree
+    if ! git diff-files --quiet --ignore-submodules --
+    then
+        echo >&2 "cannot $1: you have unstaged changes."
+        git diff-files --name-status -r --ignore-submodules -- >&2
+        err=1
     fi
+
+    # Disallow uncommitted changes in the index
+    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
+    then
+        echo >&2 "cannot $1: your index contains uncommitted changes."
+        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
+        err=1
+    fi
+
+    if [ $err = 1 ]
+    then
+        echo >&2 "Please commit or stash them."
+        return 1
+    fi
+
+    return 0
 }
 
 # Update dotfiles
 echo Updating dotfiles:
 pushd $ZSH
-if [ git_clean == true ]; then
-    git pull
+cleanTree=require_clean_work_tree
+if [ $cleanTree == 0 ]; then
+    git pull --prune --rebase
 else
     echo -e "\t" Commit changes in dotfiles first
 fi
